ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
ccflags-$(CONFIG_MULTI_CAMERA_DEEN) += -DMULTI_CAMERA_DEEN
